#!/bin/bash

# Auto-Build Environment Setup
# cocotb 2.0.1 Migration
# Generated by Planner Agent - Session 1

set -e

echo "========================================"
echo "cocotb 2.0.1 Migration Environment"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Check Python version
echo "Checking Python version..."
PYTHON_VERSION=$(python3 --version 2>&1 | awk '{print $2}')
PYTHON_MAJOR=$(echo $PYTHON_VERSION | cut -d. -f1)
PYTHON_MINOR=$(echo $PYTHON_VERSION | cut -d. -f2)

if [ "$PYTHON_MAJOR" -lt 3 ] || ([ "$PYTHON_MAJOR" -eq 3 ] && [ "$PYTHON_MINOR" -lt 6 ]); then
    echo -e "${RED}ERROR: Python 3.6+ required, found $PYTHON_VERSION${NC}"
    exit 1
fi
echo -e "${GREEN}Python $PYTHON_VERSION OK${NC}"

# Check for required simulators
echo ""
echo "Checking for Verilog simulators..."

if command -v iverilog &> /dev/null; then
    echo -e "${GREEN}Icarus Verilog found: $(iverilog -v 2>&1 | head -1)${NC}"
    export SIM="icarus"
elif command -v verilator &> /dev/null; then
    echo -e "${GREEN}Verilator found${NC}"
    export SIM="verilator"
else
    echo -e "${YELLOW}WARNING: No Verilog simulator found${NC}"
    echo "Install Icarus Verilog: sudo apt-get install iverilog"
    echo "Or Verilator: https://verilator.org/guide/latest/install.html"
fi

# Install cocotb 2.0.1
echo ""
echo "Installing cocotb 2.0.1 and pytest..."
pip install cocotb==2.0.1 pytest -q

# Verify installation
echo ""
echo "Verifying installation..."
COCOTB_VERSION=$(python3 -c "import cocotb; print(cocotb.__version__)" 2>/dev/null || echo "NOT INSTALLED")

if [ "$COCOTB_VERSION" == "NOT INSTALLED" ]; then
    echo -e "${RED}ERROR: cocotb installation failed${NC}"
    exit 1
fi

if [ "$COCOTB_VERSION" != "2.0.1" ]; then
    echo -e "${YELLOW}WARNING: cocotb version is $COCOTB_VERSION, expected 2.0.1${NC}"
    echo "Installing correct version..."
    pip install cocotb==2.0.1 --force-reinstall -q
    COCOTB_VERSION=$(python3 -c "import cocotb; print(cocotb.__version__)")
fi

echo -e "${GREEN}cocotb $COCOTB_VERSION installed${NC}"

# Show current test status (before migration)
echo ""
echo "========================================"
echo "Current Test Status (Before Migration)"
echo "========================================"
echo "Running test to show current state..."
echo ""

# Run test (will likely fail with cocotb 1.x code on 2.0)
if pytest -v test.py -k test_simple_counter 2>&1 | tail -20; then
    echo -e "${GREEN}Test already passes${NC}"
else
    echo -e "${YELLOW}Test expected to fail before migration${NC}"
fi

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "To continue building this spec, run:"
echo ""
echo "  source ../.venv/bin/activate && python ../../run.py --spec 001 --parallel 2"
echo ""
echo "Or manually run tests:"
echo "  pytest -v test.py"
echo ""
echo "Enable waveform dump:"
echo "  COCOTB_VCD=1 pytest -v test.py"
echo ""
