
// Generated by Cadence Genus(TM) Synthesis Solution 19.15-s090_1
// Generated on: Nov 22 2020 15:19:14 CET (Nov 22 2020 14:19:14 UTC)

// Verification Directory fv/chip 

module chip(odata_r, clk1, clk2, idata);
  input clk1, clk2, idata;
  output odata_r;
  wire clk1, clk2, idata;
  wire odata_r;
  wire idata_clk1_r, odata_m;
  DFFPOSX1 odata_r_reg(.CLK (clk2), .D (odata_m), .Q (odata_r));
  DFFPOSX1 odata_m_reg(.CLK (clk2), .D (idata_clk1_r), .Q (odata_m));
  DFFPOSX1 idata_clk1_r_reg(.CLK (clk1), .D (idata), .Q (idata_clk1_r));
endmodule

